"""rating ustun qo'shildi

Revision ID: a505c83c4f37
Revises: ce4f51e01d9d
Create Date: 2026-05-08 14:35:21.295319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a505c83c4f37'
down_revision: Union[str, Sequence[str], None] = 'ce4f51e01d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'rating')
    # ### end Alembic commands ###
