"""salom ustun qo'shildi

Revision ID: d691dc733ffd
Revises: a505c83c4f37
Create Date: 2026-05-08 14:44:34.174470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd691dc733ffd'
down_revision: Union[str, Sequence[str], None] = 'a505c83c4f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('salom', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'salom')
    # ### end Alembic commands ###
